# Generated by Django 3.0.5 on 2020-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_res_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
