# Generated by Django 3.0.5 on 2020-04-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_res_api', '0002_auto_20200404_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
